### ISSUE TITLE
Support for Profile Pictures

### ISSUE THREAD

**Issue by ralphschindler** [onelogin/onelogin-php-sdk#7]
Does the API or SDK somehow support updating profile pictures?

Thanks,
Ralph Schindler

**Comment by pitbulk** [comment]
Not atm.

**Comment by ralphschindler** [comment]
Do you want me to leave this open as a feature request or close it? I actually don’t see support for pictures in the API either, maybe that could be a feature request for the API?

**Comment by pitbulk** [comment]
Ideas/Feature requests should be sent to https://onelogin.ideas.aha.io

**Comment by ralphschindler** [comment]
Will do. thanks!
